project_id = "dnnyinjoztaihzcvdymj"
[functions.create-pix-payment]
enabled = true
verify_jwt = true
import_map = "./functions/create-pix-payment/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/create-pix-payment/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/create-pix-payment/*.html" ]

[functions.mercado-pago-webhook]
enabled = true
verify_jwt = false # O webhook é verificado com assinatura, não JWT
import_map = "./functions/mercado-pago-webhook/deno.json"
entrypoint = "./functions/mercado-pago-webhook/index.ts"

[functions.request-withdrawal]
enabled = true
verify_jwt = true # Apenas usuários logados podem chamar
import_map = "./functions/request-withdrawal/deno.json"
entrypoint = "./functions/request-withdrawal/index.ts"

[functions.handle-withdrawal]
enabled = true
verify_jwt = true # Apenas admins logados podem chamar
import_map = "./functions/handle-withdrawal/deno.json"
entrypoint = "./functions/handle-withdrawal/index.ts"
