-- Adicionar coluna is_admin na tabela auth.users
-- Este arquivo de migração foi intencionalmente esvaziado.
-- A coluna `is_admin` não pode ser adicionada diretamente à tabela `auth.users`.
-- A verificação de admin será feita através de uma função SQL que lê os metadados do usuário.